### ISSUE TITLE
[Feature] Generate first example component to eliminate confusion

### ISSUE THREAD

**Issue by tayambamwanza** [ng-doc/ng-doc#112]
### Description

I spent a decent amount of time looking for where import {NG_DOC_ROUTING, provideNgDocContext} from '@ng-doc/generated';
comes from, when you do an automatic install or even a manual one, this import shows as an error and it makes you think you did something wrong, when in fact you just need to run something like ```ng g @ng-doc/builder:page "Welcome"``` for the first time.

I see I'm not the first one who got confused wondering where @ng-doc/generated comes from, so I think it can be a real source of confusion especially for first use of the library.

### Proposed solution

Could the command ```ng g @ng-doc/builder:page "Welcome"``` maybe be run in the automatic installation and added as an instruction in manual installation.

### Alternatives considered

Add a note in documentation of why @ng-doc/generated is initially missing

**Comment by skoropadas** [comment]
Hi, thank you for the ticket! Actually, you need to run the application for the first time using `ng serve`. When launching the NgDoc application, it will generate files for `@ng-doc/generated`, and adding a page won't create these files. However, I think it's worth mentioning this in the installation guide.

I will add a note about this in the installation uide, as well as an additional message when using automatic installation with the command `ng add @ng-doc/add`.

**Comment by tayambamwanza** [comment]
> Hi, thank you for the ticket! Actually, you need to run the application for the first time using `ng serve`. When launching the NgDoc application, it will generate files for `@ng-doc/generated`, and adding a page won't create these files. However, I think it's worth mentioning this in the installation guide.
> 
> I will add a note about this in the installation uide, as well as an additional message when using automatic installation with the command `ng add @ng-doc/add`.

Thank you, the strange this is when I ran ng serve the error remained, it's only when I used ng add that it disappeared :\
