### ISSUE TITLE
[Docs] Nx automatic installation should have --project flag

### ISSUE THREAD

**Issue by tayambamwanza** [ng-doc/ng-doc#115]
### Description

When I ran 
```
npm install @ng-doc/add && npx nx g @ng-doc/add:ng-add
```

It configured the default project, but it was an alternative project that I wanted configured

I believe

```
npm install @ng-doc/add && npx nx g @ng-doc/add:ng-add --project project-name
```

Would be a better command on the docs website

I am willing to create a pull request.

**Comment by skoropadas** [comment]
I agree 👍 you can create a PR if you want
