### ISSUE TITLE
[Bug] Upgrade from `16.16.0` to `17.1.3` results in the error `ambiguous indirect export: parse`

### ISSUE THREAD

**Issue by janilein** [ng-doc/ng-doc#117]
### Is this a regression?

Yes

### Description

Hi!

I just upgraded to Angular 17 and version `17.1.3` of ng-doc. The migration was pretty straightforward, however every page with a demo or playground cannot be loaded anymore. When you try to go to the page an error is thrown. If you remove the demo's and playgrounds from `NgDocPage`. You can route to the page and the markdown is displayed. I do not immediately see what the issue could be..

I hope this information is enough.

### Please provide the exception or error you saw

```true
ERROR SyntaxError: ambiguous indirect export: parse
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Firefox

### Node version

18.17.1

**Comment by skoropadas** [comment]
It's gonna be a challenge to find bug, do you have anything that could help me? maybe repo or steps to reproduce?

**Comment by janilein** [comment]
I can't provide the repo unfortunately. However, I digged a bit further and found the following: In the demo and playground components, I use components from an angular library defined in the repo aswell. 

```
import {Component} from '@angular/core';
import {CommonModule} from '@angular/common';
import {DividerComponent} from '@my/lib';

@Component({
  selector: 'doc-basic-divider-demo',
  templateUrl: './basic-divider-demo.component.html',
  styleUrls: ['./basic-divider-demo.component.scss'],
  standalone: true,
  imports: [CommonModule, DividerComponent],
})
export class BasicDividerDemoComponent {

}
```
Gives the error, but 
```
import {Component} from '@angular/core';
import {CommonModule} from '@angular/common';
//import {DividerComponent} from '@my/lib';

@Component({
  selector: 'doc-basic-divider-demo',
  templateUrl: './basic-divider-demo.component.html',
  styleUrls: ['./basic-divider-demo.component.scss'],
  standalone: true,
  //imports: [CommonModule, DividerComponent],
})
export class BasicDividerDemoComponent {

}
```
Does not give an error.

With the `index.d.ts` file from library containing
```
/**
 * Generated bundle index. Do not edit.
 */
/// <amd-module name="@my/lib" />
export * from './public-api';
```

I hope that this gives a bit more information. I'll look further into it aswell and keep you posted.

**Comment by janilein** [comment]
Okay, I got it working again after changing the import to
```
import {Component} from '@angular/core';
import {CommonModule} from '@angular/common';
import {DividerComponent} from '../../../../../../../../mylib/src/lib/divider';

@Component({
  selector: 'doc-basic-divider-demo',
  templateUrl: './basic-divider-demo.component.html',
  styleUrls: ['./basic-divider-demo.component.scss'],
  standalone: true,
  imports: [CommonModule, DividerComponent],
})
export class BasicDividerDemoComponent {

}
```

What do you think is the proper solution?

**Comment by janilein** [comment]
Okay I see, I can change it to the source code. This was not clear to me that it needed to be like this.

However, it worked before with the compiled library and I think this is an interesting use case.

**Comment by janilein** [comment]
Could it have something to do with the switch from webpack to vite?

**Comment by janilein** [comment]
Thank you for the feedback and support! I will look into it. 

I was not sure if I would keep the docs together with lib in one repo, that's why I used the compiled lib for everything. I know that it would not work for the playground, but I made a wrapper component for this. The wrapper is not ideal, so I will probably switch to using the source.

**Comment by skoropadas** [comment]
I see, but I think it's good to have docs in the same repo, it's easier to keep your docs up to date and ask your contributors about it in the PRs.

Anyways, I'll close the issue, feel free to reopen it again!
