### ISSUE TITLE
Update @ngneat/until-destroy to 10.0.0

### ISSUE THREAD

**Issue by djay1977** [ng-doc/ng-doc#127]
https://github.com/ng-doc/ng-doc/blob/f08373d4cf169be8f1c31d07e05f5d2c8364da4d/package.json#L62

**Comment by skoropadas** [comment]
do you have any issues with that?

**Comment by djay1977** [comment]
I use version 10 (latest) in my projects but with NgDoc, I have a peer dependencies error in npm install. I then have to do a -force

**Comment by skoropadas** [comment]
got it, I'll fix it today

**Comment by djay1977** [comment]
Thanks
