### ISSUE TITLE
[Feature] Demo component input support

### ISSUE THREAD

**Issue by R-Bower** [ng-doc/ng-doc#132]
### Description

I cannot pass input properties to demo components using NgDocActions.demo.  This makes it very difficult to reuse the same demo component with different properties.

Currently we can pass inputs to playground components:
```
{{ NgDocActions.playground("ButtonPlayground", {inputs: {size: "small"} }) }}
```

The goal is to be able to reuse the same demo component with different inputs.

```
{{ NgDocActions.demo("ButtonDemo", {inputs: {size: "small"}} }) }}
```

### Proposed solution

Be able to pass input properties to components created with NgDocActions.demo.

### Alternatives considered

None

**Comment by skoropadas** [comment]
You are talking about inputs for the demo component, not about the component that is used in the demo right?

**Comment by R-Bower** [comment]
Yes, that's correct.

**Comment by skoropadas** [comment]
Ok, should be easy to do, I'll release it on the weekend!
