### ISSUE TITLE
[Bug] 'Multiple API Configurations' causes build error

### ISSUE THREAD

**Issue by HowardSeong** [ng-doc/ng-doc#133]
### Is this a regression?

I don't know

### Description

Hi, I'm trying to use [Multiple API configurations](https://ng-doc.com/docs/file-entities/api#multiple-api-configurations) feature with 2 `ng-doc.api.ts` files, and it causes an error below while building an application.
>✘ [ERROR] Could not resolve "./ng-doc.api-list.json"
>
>  ng-doc/plugin-api-doc/api/api0/ng-doc-api-list.module.ts:4:20:
>   4 │ import apiList from './ng-doc.api-list.json';

I have debugged build steps, and I found out `APIListEntity` is being destroyed on build process.
Eventually, it fails to generate `ng-doc.api-list.json` file for an `APIEntity`.
As I guess, it fails to build because `APIListEntity` uses same `id`, `"NgDocIndexFile"`.
In a `set` method of `NgDocEntityStore`, one of APILists is being removed, as it uses same key `"NgDocIndexFile"` for each `APIListEntity` instance.

```ts
override set(key: string, value: NgDocEntity): this {
    if (this.get(key) !== value) {
	this.get(key)?.destroy();
    }

    return super.set(key, value);
}
```

### Please provide the exception or error you saw

```true
While building ng doc application, it shows error below

✘ [ERROR] Could not resolve "./ng-doc.api-list.json"

    ng-doc/plugin-api-doc/api/api0/ng-doc-api-list.module.ts:4:20:
      4 │ import apiList from './ng-doc.api-list.json';
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~
```

### OS

Unix (Linux, macOS, etc.)

### Browser

None

### Node version

18.16.0

**Comment by skoropadas** [comment]
Hey, big thanks for the ticket and help! You are right, it's a mistake with id that I made several months ago when I was refactoring all these classes. I'll release a fix right now.
