### ISSUE TITLE
[Bug] Playground 'recreate' doesn't seem to be working

### ISSUE THREAD

**Issue by safraja** [ng-doc/ng-doc#138]
### Is this a regression?

I don't know

### Description

When I try (even in the ngdoc documentation: [https://ng-doc.com/docs/guides/playground](https://ng-doc.com/docs/guides/playground)) to use the 'recreate' option in playground, the component is usually not remade. Only the code preview changes, but the component stays the same (ng-doc-tag) or sometimes even disappears (ng-doc-button).

I have observed this behavior in both Firefox 123 and Edge 122. No error is displayed in the browser console.

![obrazek](https://github.com/ng-doc/ng-doc/assets/63454672/770efcdf-9e0f-43b5-a4bf-c12d7f71433d)

### OS

Windows

### Browser

Firefox

### Node version

20.9

**Comment by skoropadas** [comment]
Yep sry, didn't notice that, should be fixed now

**Comment by safraja** [comment]
Thanks again for all the quick fixes. 🙂

**Comment by skoropadas** [comment]
> Thanks again for all the quick fixes. 🙂 

Thank you for the findings 👍
