### ISSUE TITLE
[Feature] Preview for SCSS if it is defined via styleUrl property

### ISSUE THREAD

**Issue by safraja** [ng-doc/ng-doc#140]
### Description

Angular 17 added an option to define component styles via `styleUrl` (instead of `styleUrls`), but ngdoc doesn't seem to recognize it in the demo and doesn't generate a preview tab for it.
![obrazek](https://github.com/ng-doc/ng-doc/assets/63454672/5309200a-ac28-4f30-b720-36a259d876ea)

### Proposed solution

Add support for the styleUrl property so that ngdoc can display the styles specified by it.

### Alternatives considered

-

**Comment by skoropadas** [comment]
Nice catch, thank you! I'll fix it tomorrow
