### ISSUE TITLE
[Feature] Display method overloads

### ISSUE THREAD

**Issue by parliament718** [ng-doc/ng-doc#143]
### Description

In the API functionality, I would like to be able to see the various method overloads of a class. I know that Typescript classes don't have method overloading, however, it's possible to use the `declare` keyword in order to define overloading signatures for documentation purposes:

```
export declare class OrderProcessor {
    getOrders(): Order[];
    getOrders(instrument: string): Order[];
    getOrders(instrument: string, portfolio: string): Order[];
}
```

Unfortuantely, even when TsDoc is provided for each, ng-doc only displays the first signature.

### Proposed solution

Display all method overloads

<img width="746" alt="Screenshot 2024-03-23 at 11 19 06 PM" src="https://github.com/ng-doc/ng-doc/assets/3580270/0d0a4036-3740-4ab8-a561-fcdf1d32aa68">

Above for demonstration

### Alternatives considered

None possible

**Comment by skoropadas** [comment]
Good one thanks! I'll add it to the new release as well

**Comment by skoropadas** [comment]
Added in NgDoc 18
