### ISSUE TITLE
[Bug] Playground Feature Not Working

### ISSUE THREAD

**Issue by zerbusdetroy** [ng-doc/ng-doc#144]
### Is this a regression?

I don't know

### Description

Hello,

I am experiencing an issue with the playground feature. I am unsure if this is a bug or if I have missed a configuration step.

Steps to reproduce:

- Create an Angular app: `ng new myapp`
- Add ng-doc: `ng add @ng-doc/add`
- Add `"baseUrl": "./"` to `tsconfig.json` (This step is not documented, but without it, the application crashes)
- Add a doc page in src: `ng g @ng-doc/builder:page "Installation"`
- Copy the demo code with a playground example (with the component aside):
```
import { FloatingCircleComponent } from './floating-circle/floating-circle.component';
import { FloatingCirclePositionControlComponent } from './floating-circle-position-control/floating-circle-position-control.component';

...

playgrounds: {
    FloatingCircle: {
      target: FloatingCircleComponent,
      template: '<ng-doc-selector></ng-doc-selector>',
    },
  },
```

Upon following these steps, I encounter the exception bellow

### Please provide the exception or error you saw

```true
✘ [ERROR] TS-993004: Unable to import component FloatingCircleComponent.
  The symbol is not exported from [...]/src/app/installation/ng-doc.page.ts (module 'src/app/installation/ng-doc.page'). [plugin angular-compiler]

    ng-doc/doc-no-ssr/guides/installation/playgrounds.ts:20:13:
      20 │ export class PlaygroundComponent1 extends NgDocBasePlayground {
         ╵              ~~~~~~~~~~~~~~~~~~~~

  The component is declared here.

    src/app/installation/floating-circle/floating-circle.component.ts:8:0:
      8 │ @Component({
        ╵ ~~~~~~~~~~~~
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

v18.18.0

**Comment by skoropadas** [comment]
Yep that's a new bug, something was changed in the last angular minor version, I'll fix it, thank you!
