### ISSUE TITLE
Amazing Work

### ISSUE THREAD

**Issue by TheNightmareX** [ng-doc/ng-doc#145]
Thank you very much for this significant contribution to the Angular ecosystem!  
Every detail in this project keeps telling me how talented you are. I haven't seen such a satisfying project in a long time. Thank you very much Alex.

When developing [layout-projection](https://github.com/TheNightmareX/layout-projection), I struggled looking for an Angular documentation engine, and ultimately decided to write myself a simple one that barely covered my use case.  
Recently, as I'm working on a new project which is a set of Angular libraries, I planeed to develop a more complete Angular documentation engine based on the previous prototype, but, suprisingly, I found this amazing project!

Haven't been so excited for a project for a while. Writing this just to let you know my endorsement :P  
Good luck and hope you success!

**Comment by skoropadas** [comment]
Thank you very much for such warm words, such feedback always provides additional motivation to continue working on the project and developing it further. Big thanks!
