### ISSUE TITLE
[Docs] Update ng-doc path in docs

### ISSUE THREAD

**Issue by bohoffi** [ng-doc/ng-doc#150]
### Description

The installation docs still reference `.ng-doc` in some points like:
- [Adding .ng-doc folder to gitignore](https://ng-doc.com/docs/getting-started/installation#adding-ng-doc-folder-to-gitignore)
- [Updating tsconfig](https://ng-doc.com/docs/getting-started/installation#updating-tsconfig)

I'd be happy to help you providing a PR to update the docs

**Comment by skoropadas** [comment]
Hi thanks for the ticket, I'd be happy to approve such PR! :)

**Comment by skoropadas** [comment]
PR is merged, closing this one. Thanks! ❤️
