### ISSUE TITLE
[Feature] Remove Google Fonts

### ISSUE THREAD

**Issue by BillLudwig** [ng-doc/ng-doc#152]
### Description

The main.css and global.css both @import Google fonts which causes build errors when used in environments that don't allow external connections for build servers. 

### Proposed solution

I would suggest moving this to the theme files so it can be easily overwritten by those of us who need or want to. 

### Alternatives considered

Another option would be to use a system font stack for improved performance.

**Comment by skoropadas** [comment]
Hey, thank you for the ticket! Honestly, I want to delete all those fonts and use the default system fonts. But it will require tweaking the design a bit, because with different fonts, the application will look a bit strange. But I hear you, I'll try to come up with something on the weekend

**Comment by BillLudwig** [comment]
Thanks for the quick reply. If you need anything let me know, happy to help.

**Comment by BillLudwig** [comment]
Awesome, thank you so much!
