### ISSUE TITLE
[Bug] input aliasing decorator selector not rendered correctly

### ISSUE THREAD

**Issue by rubenprins** [ng-doc/ng-doc#155]
### Is this a regression?

I don't know

### Description

When you have a decorator input that has a template name that aliases the decorator's attribute selector, the demo code rendered is incorrect, because the selector is rendered as-is (without square brackets or value), and then the input is rendered too, in square brackets, but with the _input_ name rather than the _template_ name.

This can be seen with the Playground > Decorators example for the `NgDocRotatorDirective`.

```ts
@Directive({
	selector: '[ngDocRotator]',
	standalone: true,
})
export class NgDocRotatorDirective implements OnChanges, OnInit {
	/** Rotator state */
	@Input('ngDocRotator')
	rotated: boolean = false;
```

Expected template when `ngDocRotator` is checked in the playground pane:

```html
<button [ngDocRotator]="true">
  Button
</button>
```

Actual:

```html
<button ngDocRotator [rotated]="true">
  Button
</button>
```
This is incorrect, because the `rotated` input's template name was aliased to `ngDocRotator`.

Note that if your input was defined as 
```ts
@Directive({
	selector: '[ngDocRotator]',
	standalone: true,
})
export class NgDocRotatorDirective implements OnChanges, OnInit {
	/** Rotator state */
	@Input()
	ngDocRotator: boolean = false;
```
then you'd get the `ngDocRotator` twice:

```html
<button [ngDocRotator]="true" ngDocRotator>
  Button
</button>
```

### Please provide the exception or error you saw

```true
No exceptions are shown.
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

N/A

### Anything else?

Additionally, it appears that if you put your component/directive attribute in square brackets in your playground template already, to demo a non-default value, the template parser doesn't find it. Probably because it looks for the non-bracketed attribute.

**Comment by skoropadas** [comment]
Thanks for the ticket I'll fix it asap!

**Comment by rubenprins** [comment]
Wow, that was really quick, thanks! Demo page looks good, and I'll try it out my own setup.

**Comment by skoropadas** [comment]
Sure! If it's a bug that breaks some functionality then yeah I'm trying to close it in one day, but features/improvements may take more time
