### ISSUE TITLE
[Bug] hidden: true in NgDocPage-Config does not avoid displaying a component in the navigation. 

### ISSUE THREAD

**Issue by BenjaminLP** [ng-doc/ng-doc#158]
### Is this a regression?

I don't know

### Description

At https://ng-doc.com/docs/api/core/interfaces/NgDocPage an attribute "hidden" is listed. Description of this attribute describe how to avoid displaying a component in documentation. It seems, that this attribute has no function at all.

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

18.13.0

### Anything else?

const Button: NgDocPage = {
  title: `myButton`,
  mdFile: './index.md',
  category: ComposedComponentsCategory,
  demos: { ButtonDemoComponent },
  imports: [ButtonComponent],
  hidden: true,
  playgrounds: { ... }
}

**Comment by skoropadas** [comment]
Well, it does exactly what the doc say "If true the page will be hidden from the sidebar", so it affects only the sidebar but not other things, do you wanna stop displaying some pages in your doc?

**Comment by skoropadas** [comment]
or you still have it in the sidebar?
