### ISSUE TITLE
[Bug] Table of contents link does not work properly with basehref

### ISSUE THREAD

**Issue by shhdharmen** [ng-doc/ng-doc#159]
### Is this a regression?

I don't know

### Description

1. Build the project with base-href, for example: `npm run build -- --base-href "/coolshapes/"`
2. Observe that links in the table of contents component are not generating link right

Demo available at [https://ngxpert.github.io/coolshapes/](https://ngxpert.github.io/coolshapes/). Go to Installation from left nav, and then click on "Usage" from right nav. It should redirect to `https://ngxpert.github.io/coolshapes/getting-started/installation#usage`, instead it's redirecting to `https://ngxpert.github.io/getting-started/installation#usage`. Notice that `/coolshapes` is missing from the href.

### OS

Windows

### Browser

Edge

### Node version

20.12.2

**Comment by shhdharmen** [comment]
You can also try to reproduce this for serve:

1. Add `"baseHref": "/coolshapes/"` in property to architect > build > options in `angular.json`
2. Serve with `ng serve --serve-path coolshapes`

Observe that bottom navigation links are working fine, but not the right table of content links.

**Comment by shhdharmen** [comment]
As a workaround, I created custom components and used them to render toc. For reference, take a look at this [commit](https://github.com/ngxpert/coolshapes/commit/c4b4f35d5a49fa9883bd2f5e9c93af20da589a19).

The main part was providing `routerLink` instead of `href` in `ToCElementComponent extends NgDocTocElementComponent`:

```html
<a
  [routerLink]="href.split('#')[0]"
  [fragment]="href.split('#')[1]"
  [style.padding-left]="'calc(var(--ng-doc-toc-indent) * ' + level + ')'"
>
  <ng-content></ng-content>
</a>

```

**Comment by skoropadas** [comment]
Hey thx for the ticket, I'll release a fix in a moment!
