### ISSUE TITLE
Support for Mermaid

### ISSUE THREAD

**Issue by amduenas07** [ng-doc/ng-doc#165]
### Discussed in https://github.com/ng-doc/ng-doc/discussions/164

<div type='discussions-op-text'>

<sup>Originally posted by **amduenas07** June  4, 2024</sup>
Is there any possibility to render a diagram with Mermaid?</div>

**Comment by skoropadas** [comment]
I'll try to add it to NgDoc 18

**Comment by amduenas07** [comment]
Do you have an estimated date?

> I'll try to add it to NgDoc 18

**Comment by skoropadas** [comment]
> Do you have an estimated date?
> 
> > I'll try to add it to NgDoc 18

Probably it's gonna take about 2 months. There are still some things that I need to check and fix It's gonna be a really big release and I wanna make sure that everything works correctly.

**Comment by skoropadas** [comment]
> @skoropadas does it mean we should wait Angular 18 support only in 2 months?

No, recently I've added a small fix, so NgDoc 17 should work with Angular 18

**Comment by skoropadas** [comment]
@dhutaryan Moreover the NgDoc docs app is already using angular 18, so I guess it works :)

**Comment by skoropadas** [comment]
Added for NgDoc 18 (https://github.com/ng-doc/ng-doc/commit/cfb941bb53e07a00894afa72cbe19ccb5ecf0ba6)

**Comment by skoropadas** [comment]
Released in NgDoc 18
