### ISSUE TITLE
[Query] Is it possible to import macros from angular library?

### ISSUE THREAD

**Issue by akhileshThapliyal** [ng-doc/ng-doc#169]
I am creating an angular library which I intend to import into my ng doc application. I want to refer to the components which are in my library so that I can maintain different documentation versions and in my library, I will have different versions of the components. For instance, I intend to have v1/docs, v2/docs applications and an angular library with v1 and v2 components.

Hence, I want to add the macro helpers as part of my library, so that I can share it in both my documentation app v1 and v2.

I did try the below, but it didn't work, it always refers to the relative path. I give me an error that the file is not found (Error: ENOENT no such file or directory) as it constructs paths as "**app/src/docs/getting-started/installation/@my-angular-lib/macros/helper.macro.md**".

```typescript
{% import "@my-angular-lib/macros/helper.macro.md"  %}
```

**Comment by skoropadas** [comment]
Yeah, it seems that nunjucks does not support the feature you're looking for. To implement the documentation in this way, I would recommend using an NX monorepo with multiple apps dedicated to documentation. This approach will allow you to have access to the source code and easily share some things between different documentation apps.

I also think that this is a good practice as it enables you to release the documentation and new library versions together. Additionally, it allows you to identify any errors that may arise during the compilation of the documentation app.

**Comment by akhileshThapliyal** [comment]
> NX monorepo

NX monorepo is similar to Angular workspace. The problem with this is still the same, I need to refer the macros with hardcoded paths like ../../../../<path to macro> and I cannot configure paths based on a configuration the way we define paths in the compiler option in tsconfig.app :(

**Comment by skoropadas** [comment]
> > NX monorepo
> 
> NX monorepo is similar to Angular workspace. The problem with this is still the same, I need to refer the macros with hardcoded paths like ../../../../<path to macro> and I cannot configure paths based on a configuration the way we define paths in the compiler option in tsconfig.app :(

Well there is no workaround for that, because nunjucks uses one file resolver for everything, so if you e.g. start having paths relative to your shared folder, then you'll need to use such paths for everything else, I could make an option for the builder to configure root path for file resolver if it will help you

**Comment by akhileshThapliyal** [comment]
> relative to your shared folder, then you'll need to use such paths for everything else, I could make an option for the builder to configure root path for file resolver if it will help you

Hi @skoropadas, np. I managed it. So I created an angular workspace where I have all the libs and projects co-exist. I am referencing using a relative path to the common macro file in one of the libs. Not sure whether this is optimal approach, but it helps me to keep the code clean, tidy and organised.

**Comment by maximLyakhov** [comment]
@skoropadas I have ng project with one library only meant to be published as package.
Currently it's described with storybook.
Tried to install **ng-doc**, but it partially failed due to absence of _app.module_.
Will **ng-doc** project support just libraries in foreseeable future?
