### ISSUE TITLE
[Bug] The id of the html header is not serialized

### ISSUE THREAD

**Issue by HyperLife1119** [ng-doc/ng-doc#172]
### Is this a regression?

I don't know

### Description

I am a Chinese developer, when I use Chinese to write documents, I found that clicking the toc can not automatically scroll to the corresponding position, because the id of the header is not serialized:

```md
## 你好
```

```html
<h2 id="你好">你好</h2>
```
When Chinese or other languages appear in the URL, we should serialize them using encodeURIComponent.

Expected Rendering Results:

```html
<h2 id="%E4%BD%A0%E5%A5%BD">你好</h2>
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

20

**Comment by skoropadas** [comment]
I'll check it thanks! I'm using github-slugger under the hood and yeah based on [their docs](https://github.com/Flet/github-slugger?tab=readme-ov-file#usage) they return language as it is, I need to check where the problem is, if need to change something on the builder side or the client side
