### ISSUE TITLE
[Bug] Support angular17html in code fences

### ISSUE THREAD

**Issue by R-Bower** [ng-doc/ng-doc#180]
### Is this a regression?

No

### Description

In an ng-doc markdown page, I am unable to use the angular17html language identifier.

The following works fine:
````
```html
<table q-table>
  <thead q-thead>
    @for (headerGroup of table.getHeaderGroups(); track: trackById) {
      <tr q-tr></tr>
    }
  </thead>
</table>
```
````

The following seems to break markdown parsing:

````
```angular17html
<table q-table>
  <thead q-thead>
    @for (headerGroup of table.getHeaderGroups(); track: trackById) {
      <tr q-tr></tr>
    }
  </thead>
</table>
```
````

### Please provide the exception or error you saw

![image](https://github.com/ng-doc/ng-doc/assets/11933208/9f51b873-d78e-49a8-a176-9db04a7ff147)

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

~20

**Comment by skoropadas** [comment]
I think it doesnt work because highlightjs that is used for highlighting doesn't have this [language](https://highlightjs.readthedocs.io/en/latest/supported-languages.html). What are you trying to achieve?

**Comment by R-Bower** [comment]
> I think it doesnt work because highlightjs that is used for highlighting doesn't have this [language](https://highlightjs.readthedocs.io/en/latest/supported-languages.html). What are you trying to achieve?

Ah I see.  I think xhtml works fine for this use case.  I believe Webstorm has support for angular17html, but it doesn't seem to be supported elsewhere.
