### ISSUE TITLE
[Feature] Support inline template syntax highlighting

### ISSUE THREAD

**Issue by R-Bower** [ng-doc/ng-doc#181]
### Description

The current syntax highlighter treats TS files as typescript (as it should).  Unfortunately this causes inline-template html to render without syntax highlighting.

![image](https://github.com/ng-doc/ng-doc/assets/11933208/4e9dfee3-fa5f-4210-9c7f-f9d2ec983820)

### Proposed solution

Can inline template segments be split out and highlighted using the html language? This would improve the appearance and readability of inline templates.

### Alternatives considered

None

**Comment by skoropadas** [comment]
Yeah, also, I wouldn't say I like how it looks. I'll check what we can do with that

**Comment by skoropadas** [comment]
Highlightjs was replaced with Shiki to support inline template syntax highlighting and will be released with NgDoc18

**Comment by skoropadas** [comment]
Released in NgDoc 18
