### ISSUE TITLE
[Query] Usage of Recreate option in the Playground

### ISSUE THREAD

**Issue by akhileshThapliyal** [ng-doc/ng-doc#182]
Hi @skoropadas,

I was wondering about the usage of the recreate option in the playground. I also read the documentation but found nothing about why we require the recreate option.

The output is the same when we check on the recreate option versus not checking it.

**With Recreate Option Checked**

<img width="821" alt="image" src="https://github.com/ng-doc/ng-doc/assets/7280745/2b712640-d024-47bd-9b86-be32c4ecf2e8">

**Without Recreate Option Checked**

<img width="814" alt="image" src="https://github.com/ng-doc/ng-doc/assets/7280745/9c23d5be-ccc1-43ac-bf9f-9f141bc66e4f">

Regards,
Akhilesh

**Comment by skoropadas** [comment]
It just recreates the playground component when inputs change. It can be useful for components with "static" inputs. For example when you have an input that is used only for calling a function in ngOnInit hook.

**Comment by skoropadas** [comment]
Can I close the ticket or do you have other questions?
