### ISSUE TITLE
[Bug] API Link Reference missing for optional properties of a component

### ISSUE THREAD

**Issue by akhileshThapliyal** [ng-doc/ng-doc#183]
### Is this a regression?

No

### Description

When we create a user-defined data type or interface and reference the inputs as optional, the document references are not linked.

**Expected Behaviour**: The API references should be able to link to the documentation irrespective of whether the attributes are optional or required.

**Suggestion**: It is better to check all the edge cases with regard to these scenarios. Thank you :)

**My Workspace**: https://github.com/akhileshThapliyal/my-ng-doc-app

**With Optional Value** (Unable to link to AriaAttributes documentation page)

<img width="450" alt="image" src="https://github.com/ng-doc/ng-doc/assets/7280745/2ead86d5-440f-44be-a684-f54539f54444">

<img width="418" alt="image" src="https://github.com/ng-doc/ng-doc/assets/7280745/2cc74ef9-0358-47e5-9ccf-e57d8cea5cf4">

<img width="829" alt="image" src="https://github.com/ng-doc/ng-doc/assets/7280745/f8a54e1e-1016-4f12-9b46-7bb55163483e">

**Without Optional Value**

<img width="450" alt="image" src="https://github.com/ng-doc/ng-doc/assets/7280745/eb8b7864-22d2-487f-83c9-50436ac576ac">

<img width="409" alt="image" src="https://github.com/ng-doc/ng-doc/assets/7280745/e2e702b3-683c-44ae-be9d-3ef0b8d3211b">

<img width="652" alt="image" src="https://github.com/ng-doc/ng-doc/assets/7280745/1be78c33-78cd-43e9-990a-d126c31dc446">

Regards,
Akhilesh

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

20.9.0

### Anything else?

Latest Version: 17.6.14

**Comment by skoropadas** [comment]
This is already fixed in NgDoc 18.

**Comment by akhileshThapliyal** [comment]
> This is already fixed in NgDoc 18.

Wow good to know, we are going to have the next release soon :) I will re-test this once 18 is released.

**Comment by skoropadas** [comment]
Released in NgDoc 18
