### ISSUE TITLE
[Query] What is ```twig fence code and what all the markdown fence code supported in Ng Docs?

### ISSUE THREAD

**Issue by akhileshThapliyal** [ng-doc/ng-doc#186]
HI @skoropadas, 

I was exploring your documentation page on [templating guides](https://ng-doc.com/docs/guides/templating). I also have a use case where I am building a macro reference guide where I want to display the macro snippets. 

I see that a fenced code of ```twig is used as shown in the screenshot below ([code](https://github.com/ng-doc/ng-doc/blob/main/apps/ng-doc/docs/guides/templating/index.md?plain=1)), however, I cannot view any reference to "twigs" on the markdown-supported languages. May I know what is the significance of this tag and what are all the options available to use it?

<img width="815" alt="image" src="https://github.com/ng-doc/ng-doc/assets/7280745/792b86a9-0c18-44db-b39e-5ef348808075">

<img width="481" alt="image" src="https://github.com/ng-doc/ng-doc/assets/7280745/1adc2d54-8b8f-432e-8128-770849a7f25c">

Markdown code block references: [link](https://docs.readme.com/rdmd/docs/code-blocks).

Is there a place where I can find all the supported languages listed in Fence Code Blocks by ng-docs?

Regards,
Akhilesh

**Comment by skoropadas** [comment]
Well the twig has the same language tokens as nunjucks, so I used it to have a highlighting for the nunjucks syntax.

By default ng-doc includes support for 40 the most popular languages, you can find them [here](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md).

I would recommend using only the most popular languages, because in NgDoc 18, I will migrate highlightjs to shiki to support angular inline templates highlighting.

**Comment by akhileshThapliyal** [comment]
> Well the twig has the same language tokens as nunjucks, so I used it to have a highlighting for the nunjucks syntax.
> 
> By default ng-doc includes support for 40 the most popular languages, you can find them [here](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md).
> 
> I would recommend using only the most popular languages, because in NgDoc 18, I will migrate highlightjs to shiki to support angular inline templates highlighting.

@skoropadas, adding these links and references to the templating guide page would be great. Thank you :)

**Comment by skoropadas** [comment]
Ok I'll keep it in mind, but for now it doesn't make too much sense since I wanna replace the highlightjs with shiki, but I'll update guides for sure, thanks! 👍
