### ISSUE TITLE
Demo/Demo Pane Crash with "Unexpected end of JSON input" [Bug] 

### ISSUE THREAD

**Issue by mlamothe** [ng-doc/ng-doc#188]
### Is this a regression?

I don't know

### Description

Crash when trying to use Demo or Demo Pane, like this: {{ NgDocActions.demo("MyDemoComponent") }}

Without going down a rabbit hole, here's the important details: I'm getting this stack dump in the console:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.extractOptions (ng-doc-app-processors-processors.mjs:43:21)
```

So we know the code that's crashing is here:

```
const demoProcessor = {
  component: NgDocDemoComponent,
  selector: 'ng-doc-demo',
  extractOptions: element => ({
    inputs: {
      componentName: element.getAttribute('componentName') || undefined,
      **options: JSON.parse(element.querySelector('#options')?.textContent ?? '') || {}**
    }
  })
};
```

Now, I don't know why, but `element.querySelector('#options')` is returning undefined (that's fine, whatever). But notice the `??` says if it's undefined, return an empty string. Well there's the crash - JSON.parse throws an exception when given an empty string. (The same code appears in `demoPaneProcessor`.)

Edit to add: This version make so difference (same crash, options is still undefined): 
`{{ NgDocActions.demo("MyDemoComponent", {container: false}) }}`

### Please provide the exception or error you saw

```true
See above.
```

### OS

Windows

### Browser

Chrome

### Node version

18.20.3

### Anything else?

Angular 18.0

**Comment by mlamothe** [comment]
Well I just found steps to reproduce! The bug is triggered by having text before the {{ }}!

Crash:
```
FOO
{{ NgDocActions.demo("MyDemoComponent") }}
```
Or
```
FOO {{ NgDocActions.demo("MyDemoComponent") }}
```

If I remove "FOO" the crash goes away =)

**Comment by skoropadas** [comment]
Ah I see, this is how marked library works but I think I could fix it by adding some whitespaces for the actions. I'll try to fix it thanks 👍

**Comment by mlamothe** [comment]
I recommend tweaking two identical statements - they're just a ticking time bomb:

The empty string here is invalid - it causes JSON.parse to throw:
`options: JSON.parse(element.querySelector('#options')?.textContent ?? '') || {}`

I believe replacing the empty string with an empty object will fix the issue:
`options: JSON.parse(element.querySelector('#options')?.textContent ?? '{}') || {};`

**Comment by skoropadas** [comment]
Since it's not urgent I'll fix it in version 18

**Comment by skoropadas** [comment]
Released in NgDoc 18
