### ISSUE TITLE
[Bug] Build / serve crash when using Angular 18.1

### ISSUE THREAD

**Issue by NetWin** [ng-doc/ng-doc#189]
### Is this a regression?

Yes

### Description

When using ng-doc within an Angular 18.1 library. The serve command immediately crashes with the exception provided below.

It seems like the Angular team removed the `@angular/cli/src/utilities/spinner` class in one of the [recent commits](https://github.com/angular/angular-cli/commit/18226c6f57fdabc54ec24ac3542a6209347e9761) that was published via the 18.1.0 release.

### Please provide the exception or error you saw

```true
> ng serve docs

An unhandled exception occurred: Cannot find module '@angular/cli/src/utilities/spinner'
Require stack:
- X:\XXX\YYY\node_modules\@ng-doc\builder\helpers\print.js
- X:\XXX\YYY\node_modules\@ng-doc\builder\helpers\index.js
- X:\XXX\YYY\node_modules\@ng-doc\builder\engine\build-ng-doc.js
- X:\XXX\YYY\node_modules\@ng-doc\builder\engine\index.js
- X:\XXX\YYY\node_modules\@ng-doc\builder\dev-server\index.js
- X:\XXX\YYY\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
See "C:\Users\NetWin\AppData\Local\Temp\ng-022FJx\angular-errors.log" for further details.
```

### OS

Windows

### Browser

None

### Node version

Node v20.13.1 | npm 10.5.2

### Anything else?

![image](https://github.com/user-attachments/assets/a09408ac-2e90-49a5-b616-0720335e2557)

**Comment by skoropadas** [comment]
Thanks I'll fix it today!

**Comment by NetWin** [comment]
Thank you! Will try it out tomorrow 💪🏼💪🏼

**Comment by brandon-cho** [comment]
@skoropadas I had the same problem above and was waiting to see this post. You fixed it and raised the version so I tried updating but I'm having this problem, is there something I'm missing?

I'm using version npm: 10.7.0, node: 20.15.0.

![스크린샷 2024-07-18 오전 9 37 02](https://github.com/user-attachments/assets/bcf7d0c3-51ae-4f43-a700-724be63959a6)

**Comment by skoropadas** [comment]
@brandon-cho try to remove `.angular`, `.nx`, `node_modules`, `package-lock.json`, install packages again and run the app

**Comment by NetWin** [comment]
FYI, we just tried it and it works. Thank you for the quick fix! ⚡🚀

**Comment by brandon-cho** [comment]
@skoropadas I did what you said, but it didn't work. The same bug was raised as an issue.

https://github.com/ng-doc/ng-doc/issues/192

**Comment by skoropadas** [comment]
@brandon-cho thanks! I've found the issue, releasing a new version

**Comment by brandon-cho** [comment]
@skoropadas Works great, thanks for the quick fix!
