### ISSUE TITLE
[Bug] Anchor seems not working with french accents

### ISSUE THREAD

**Issue by Nxtivision** [ng-doc/ng-doc#190]
### Is this a regression?

No

### Description

I completely forgot to raise this bug I encounter since the beginning of the project 😜 

I have anchor like this:
> Sélection par défaut (optionnel)

In markdown, it is:
```markdown
#### Sélection par défaut (optionnel)
```

When I click on the anchor to share it, here is how it is translated inside the URL:

`http://localhost:4200/one-libraries/one-theme/radio#s%25C3%25A9lection-par-d%25C3%25A9faut-optionnel`

And when I refresh the page, it does not scroll directly to this specific title.
Did I do something wrong ? Or is it something you have to handle ? 

Thank you in advance for your help 😄 

### OS

Windows

### Browser

Chrome

### Node version

20.13.1

**Comment by skoropadas** [comment]
I am unable to reproduce the bug where the page does not scroll to the header after refreshing. Do you have a demo where I could see this?

This bug was present before, but it was resolved within #172

**Comment by Nxtivision** [comment]
My bad, I was on the previous version just before this fix :)

Sorry for the inconvenience!

**Comment by skoropadas** [comment]
> My bad, I was on the previous version just before this fix :)
> 
> Sorry for the inconvenience!

No problem! 🙂
