### ISSUE TITLE
[Bug] Component's '@Input set <property>' is not showed in Playground and is showed in the 'Accessors', not in the 'Properties' of Component's API page

### ISSUE THREAD

**Issue by azekammi** [ng-doc/ng-doc#197]
### Is this a regression?

Yes

### Description

I'm using v15.13.0 of project

Component's ts file looks like:

`import { ChangeDetectionStrategy, Component, HostBinding, Input } from '@angular/core';
    
    export type StatusChipType = 'success' | 'warning' | 'danger' | 'info';
    
    @Component({
      standalone: true,
      selector: 'uck-status-chip',
      template: '{{ text }}',
      styleUrls: ['./status-chips.component.sass'],
      changeDetection: ChangeDetectionStrategy.OnPush,
    })
    export class StatusChips {
      /**
       * Text for displaying
       */
      @Input() text: string;
      @Input() set type(value: StatusChipType) {
        this.innerType = value;
    
        this.resetTypeClass();
        this.setTypeClass();
      }
    
      get type(): StatusChipType {
        return this.innerType;
      }
    
      private innerType: StatusChipType;
    
      @HostBinding('class.status_success') private successTypeClass: boolean;
      @HostBinding('class.status_warning') private warningTypeClass: boolean;
      @HostBinding('class.status_danger') private dangerTypeClass: boolean;
      @HostBinding('class.status_info') private infoTypeClass: boolean;
    
      private resetTypeClass(): void {
        this.successTypeClass = false;
        this.dangerTypeClass = false;
        this.warningTypeClass = false;
        this.infoTypeClass = false;
      }
    
      private setTypeClass(): void {
        switch (this.innerType) {
          case 'success':
            this.successTypeClass = true;
            break;
          case 'danger':
            this.dangerTypeClass = true;
            break;
          case 'info':
            this.infoTypeClass = true;
            break;
          case 'warning':
            this.warningTypeClass = true;
        }
      }
    }`

'ng-doc.dependencies.ts' of the doc page looks like:

`import { NgDocDependencies } from '@ng-doc/core';
    import { StatusChips } from '@uk/uc-kit/components';
    import { StatusChipsDemoComponent } from './demo/status-chips-demo/status-chips-demo.component';
    import { StatusChipsPageModule } from './ng-doc.module';
    
    const StatusChipsPageDependencies: NgDocDependencies = {
      module: StatusChipsPageModule,
      demo: {
        StatusChipsDemoComponent,
      },
      playgrounds: {
        StatusChipsPlayground: {
          target: StatusChips,
          template: `<ng-doc-selector></ng-doc-selector>`,
        },
      },
    };
    
    export default StatusChipsPageDependencies;`

<img width="826" alt="Screenshot 2024-08-04 at 16 26 13" src="https://github.com/user-attachments/assets/0b187461-2c04-4b32-8554-e429d9d68ab9">
<img width="835" alt="Screenshot 2024-08-04 at 16 26 46" src="https://github.com/user-attachments/assets/4e3dfdde-eeb9-4fcd-9a60-a78ec5e5dc71">
<img width="828" alt="Screenshot 2024-08-04 at 16 27 00" src="https://github.com/user-attachments/assets/f8a11a79-257f-4cf4-b20c-dacd3a0e37c9">

### OS

Unix (Linux, macOS, etc.)

### Browser

None

### Node version

16.20.2

**Comment by skoropadas** [comment]
This bug was present before and was fixed in #116. Unfortunately, I cannot maintain and release multiple major versions at once. Even the Angular team does not provide such support for Angular. I am the sole developer working on the project and I do this only in my personal time. Such support would greatly slow down the library support because I am still working on the main features.

I would recommend updating to a newer version where this issue is resolved or use regular inputs and `data-` attributes to style your component, for example like [here](https://github.com/ng-doc/ng-doc/blob/main/libs/ui-kit/components/tag/tag.component.ts).
