### ISSUE TITLE
[Bug] Missing entries in Sidebar

### ISSUE THREAD

**Issue by NetWin** [ng-doc/ng-doc#200]
### Is this a regression?

Yes

### Description

We currently have 78 ng-doc pages (and 66 api scopes). With version 17 these were correctly rendered in the sidebar, grouped by their defined category. 

<details>
  <summary>Demo, obfuscated</summary>
  
  ![image](https://github.com/user-attachments/assets/36758f67-b014-488e-850c-92b577ba22ca)

</details>

Since updating to 18.0.1, not all pages are picked up the the builder and only a hand full (random number, sometimes 5 sometimes 7 and rarely all) of pages are displayed in the sidebar (included in the `NG_DOC_ROUTING` array).

<details>
  <summary>Demo, obfuscated</summary>
  
  ![image](https://github.com/user-attachments/assets/0fc67e88-1e70-4ab2-8133-fbba49fa0997)

</details>

It seems like everything works locally but as soon as we publish it to S3 via Github Actions some entries are missing. And it's not a problem with uploading the files itself because all 1000+ chunks are pushed to S3. As written above, the entries are completely missing in the build output.

![image](https://github.com/user-attachments/assets/b5c36d8f-0d09-490c-8921-264b9d8ef4b6)
<sup>Only a few entries are included in the build output</sup>

My un-educated guess would be something like a missing `await` that would wait until all files are written before the routing array is written to the `@ng-doc/generated` output. And i guess my pc is faster than github actions so that these files are already written when the generated fileds are created.

### Please provide the exception or error you saw

```true
There is no error thrown anywhere. the entries are simply missing.
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

v20.16.0

**Comment by skoropadas** [comment]
Hmm, I'll try to release a fix for this bug today. It may be necessary to go through several iterations, as it is difficult to understand the necessary environment for reproduction.

**Comment by NetWin** [comment]
@skoropadas You can also send me some rc versions. You don't have to release full versions for testing. 👍 
Or, if you have some hints, i could try it out in a fork and play around with it myself.

**Comment by skoropadas** [comment]
@NetWin I have added a fix in 18.0.2 along with some other minor fixes. If this is what I think it is, then solving the problem will take some time. So pls let me know if this quick fix helps

**Comment by NetWin** [comment]
FYI the first deployment went through and it looks good so far! 🚀 
I'll do 2-3 more deployments just to be sure.

But thank you for the quick response already ⚡

**Comment by skoropadas** [comment]
@NetWin sounds promising 😄 

No problem! If a bug is making it impossible to work with the library, I try to fix it as quickly as possible.

**Comment by NetWin** [comment]
After two more deployments, the issue seems to be gone! 💪 
Thank you very much for your quick response. 

We switched from Storybook to ng-doc a few months ago and love it so far! 
Great tool and the v18 update brought some really nice toys i'm looking forward to play around with soon. 😄
