### ISSUE TITLE
[Bug] Can't render APIs after upgrade to 18.x

### ISSUE THREAD

**Issue by DaveMBush** [ng-doc/ng-doc#201]
### Is this a regression?

Yes

### Description

First, I love this project. It is the only documentation engine that does what I was looking for. If it could also compete with StoryBook life would be perfect 😁.

I could not run the schematic, so I'm doing the upgrade manually so I may have missed something. (The schematic just ran and hung with no messages and I left it running for far longer than was reasonable... 1/2 an hour)

At this point, everything seems to work except for the APIs which, as far as I can tell from the documentation, have no changes from the previous version but do allow us to configure the output, which I'm not using.  I looked at how you've implemented it for the ng-docs documentation, and it doesn't look like you are using that feature either.

When I do the development build for localhost, I can't see any of my APIs and they don't show up when I search.

When I do a production build, I do see the api-list.json shows up in the assets directory.

The branch I'm working in is located here https://github.com/DaveMBush/SmartNgRX/tree/dmb/dependency-updates-2024-08-27/599

- I'm doing a production build into /ng-doc/documentation
- The raw documentation files are in /apps/documentation
- The ng-doc.api.ts is in /apps/documentation/src/app/ng-doc.api.ts
- The working, previous, version is located at https://github.com/DaveMBush/SmartNgRX and rendered at https://davembush.github.io/SmartNgRX/
- I'm running in Windows/WSL/Ubuntu 24

Let me know if you need more information.

### Please provide the exception or error you saw

No error message

### OS

 Windows/WSL/Ubuntu 24

### Browser

Edge

### Node version

20.14.0

**Comment by DaveMBush** [comment]
found it. the intermediate build now goes into `ng-doc/**` instead of `.ng-doc/**` which means the assets glob:

```
{
  "glob": "**/*",
  "input": ".ng-doc/[app-specific-stuff]",
  "output": "assets/ng-doc"
},
```

needs to change to

{
  "glob": "**/*",
  "input": "ng-doc/[app-specific-stuff]",
  "output": "assets/ng-doc"
},

**Comment by skoropadas** [comment]
I was just about to check this bug. 😄 

However, yes, it changed back in version 17.x because after the latest update of Angular and its vite builder, changes in folders starting with a dot stopped being tracked, so I had to rename them. But thanks for sharing the solution! ❤️
