### ISSUE TITLE
[Bug] Not building with lots of "Could not resolve" errors

### ISSUE THREAD

**Issue by danielsharvey** [ng-doc/ng-doc#202]
### Is this a regression?

I don't know

### Description

Used an Nx angular monorepo and a `nx g @ng-doc/add:ng-add` install.

The serve target products lots of errors like:
```
$ nx serve ng-doc-test

> nx run ng-doc-test:serve:development

Initial chunk files | Names         |  Raw size
polyfills.js        | polyfills     |  90.23 kB | 
main.js             | main          |  35.91 kB | 
styles.css          | styles        |  28.05 kB | 
chunk-VUJOFXKG.js   | -             | 938 bytes | 

                    | Initial total | 155.13 kB

Lazy chunk files    | Names         |  Raw size
chunk-YF6KN6HU.js   | page          |   2.26 kB | 
chunk-GTOJR74B.js   | page          |   2.01 kB | 

Application bundle generation complete. [1.592 seconds]

Watch mode enabled. Watching for file changes...
NOTE: Raw file sizes do not reflect development server per-request transformations.
  ➜  Local:   http://localhost:4200/
  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "@ngneat/until-destroy"

    node_modules/@ng-doc/app/fesm2022/ng-doc-app-directives-route-active.mjs:7:45:
      7 │ import { untilDestroyed, UntilDestroy } from '@ngneat/until-destroy';
        ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@ngneat/until-destroy" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@ng-web-apis/common"

    node_modules/@ng-doc/app/fesm2022/ng-doc-app-services-store.mjs:3:30:
      3 │ import { LOCAL_STORAGE } from '@ng-web-apis/common';
        ╵                               ~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@ng-web-apis/common" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

```

### Please provide the exception or error you saw

```true
See above
```

### OS

Unix (Linux, macOS, etc.)

### Browser

None

### Node version

v18.20.1

**Comment by skoropadas** [comment]
Have you tried to remove node_modules and package-lock.json file and install it again? Feels like npm doesn't want to install those packages by some reason

**Comment by danielsharvey** [comment]
I tried that. Having looked closer, it looks like you have several packages that are dependencies of your monorepo but not of the packages installed per your instructions or the generator (`npm i @ng-doc/{core,builder,ui-kit,app}`)

What I needed to install manually:
```
npm i @ng-web-apis/common @ngneat/until-destroy di-controls @tinkoff/ng-polymorpheus
```

**Comment by skoropadas** [comment]
They are peerDependencies of @ng-doc/* packages, I tested installation in a empty project and it worked for me. What version of npm are you using?

**Comment by ousc** [comment]
> @ng-web-apis/common @ngneat/until-destroy di-controls @tinkoff/ng-polymorpheus



> They are peerDependencies of @ng-doc/* packages, I tested installation in a empty project and it worked for me. What version of npm are you using?
It is indeed not installed automatically at present, which may be related to the package manager

**Comment by danielsharvey** [comment]
> They are peerDependencies of @ng-doc/* packages, I tested installation in a empty project and it worked for me. What version of npm are you using?

Interesting, I'd not noticed this. 

I'm using node v18.20.1 and npm 10.5.0.

My example was a standard Nx generator for an Angular monorepo plus your Nx add generator.

Might be a `legacy-peer-deps` issue?

I have this in my `~/.npmrc` file as I have a number of projects that break otherwise:
```
legacy-peer-deps=true
```

**Comment by skoropadas** [comment]
@danielsharvey, this is actually it, the `legacy-peer-deps` flag [forces](https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps) npm to revert to the behavior prior to npm v7, where peerDependencies aren't automatically resolved and installed. I would suggest using this flag only for projects that specifically require it. E.g. you can create a `.npmrc` file in the root folder of such projects and set the flag there and push it.

**Comment by danielsharvey** [comment]
@skoropadas Thanks
