### ISSUE TITLE
[Bug] Two different categories with the same folder name in different folders were incorrectly merged

### ISSUE THREAD

**Issue by ousc** [ng-doc/ng-doc#204]
### Is this a regression?

Yes

### Description

Hello, after upgrading from 17.x to 18.0.2, some problems seem to occur.

**Docs from two different categories (category A and category B) were mistakenly merged together, even though the route and children of the two categories were completely different.**

[Here](https://github.com/ousc/ng-doc-18-test.git) is a minimal example I could build to reproduce the problem.

> project structure.

```
├── src
│   └──docs
│       ├── comp1
│       │    └── someName
│       │         └── ng-doc.category.ts(Category1)
│       └── comp2
│            └── someName
│                 └── ng-doc.category.ts(Category2)
```

![aad4b5535a0ce655b22f0de027a357c1](https://github.com/user-attachments/assets/eae8fedf-071c-40c9-81a3-189f8bf1d78a)

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

20

**Comment by ousc** [comment]
Actual display: 
![d332abacef56d1e3ba28447db56be468](https://github.com/user-attachments/assets/b6878de8-b02c-4100-bae4-8039795e1a4d)

In version 17.x, they can be correctly displayed in two menus

**Comment by skoropadas** [comment]
I'll check that thanks!

**Comment by skoropadas** [comment]
Should be fixed now. But yeah if no route is specified, your categories would be merged into one because the folder name is used as a route by default.

**Comment by ousc** [comment]
> Should be fixed now. But yeah if no route is specified, your categories would be merged into one because the folder name is used as a route by default.

You are right, thanks for the quick fix!
