### ISSUE TITLE
[Bug] Change Detection Interference in a Page

### ISSUE THREAD

**Issue by jingglang** [ng-doc/ng-doc#205]
### Is this a regression?

I don't know

### Description

Thank you for NgDoc. It is awesome. I use it for my workplace library documentation

I have problem with demo component not refreshing it self when it's put in a page. I have removed the `changeDetection: ChangeDetectionStrategy.OnPush` from `app.component.ts`.

This link is the component not in a page. It works properly. Please alternate between the 3 buttons to redraw the table.

https://ngx-panemu-table.panemu.com/grouped-column

If you go to below link in which the same component is inside a page, now user have to click each button twice in order to refresh the table:

https://ngx-panemu-table.panemu.com/columns/grouped-column

If I put back the OnPush change detection in `app.component.ts` both URLs behave the same.

I think the problem is in my library because I don't see similar problem in other pages.

Please let me know if you have any insight.

### Please provide the exception or error you saw

```true
There is no error in web console
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

v20.14.0

### Anything else?

This problem happens on Chrome and Firefox. I didn't test on other browser.

**Comment by skoropadas** [comment]
Thanks! I'll try to check it today

**Comment by jingglang** [comment]
I managed to make it work by using onPush change detection in my lib.
