### ISSUE TITLE
[Bug] html-minifier vulnerability

### ISSUE THREAD

**Issue by AdrianKokot** [ng-doc/ng-doc#206]
### Is this a regression?

Yes

### Description

With ng-doc/builder 18 the html-minifier package was added which is not maintained and reports vulnerability - https://github.com/advisories/GHSA-pfq8-rq6v-vf5m. In issue 2022 you can find comments about maintained fork of this solution that fixed this vulnerability: https://github.com/kangax/html-minifier/issues/1135.

Would it be possible to switch to another fork to fix this reported vulnerability? I would like to use ng-doc 18, but my builds won't pass CI because npm audit reports vulnerabilities.

### OS

Unix (Linux, macOS, etc.)

### Browser

None

### Node version

20.14.0

**Comment by AdrianKokot** [comment]
I can work on PR with fix if there's no specific reason for using particularly `kangax/html-minifier`?

**Comment by skoropadas** [comment]
@AdrianKokot I would highly appreciate it. As far as I remember I used it for actions, you can replace it for sure but I would check that the content rendered by the actions is displayed correctly. The marked library that is used to convert markdown to html is very space sensitive, that's actually why I used the minifier.
