### ISSUE TITLE
[Feature] Reflect `@returns` tag contents in return type

### ISSUE THREAD

**Issue by AdrianKokot** [ng-doc/ng-doc#219]
### Description

Currently, if there's some additional text in `@returns` JSDoc tag, the contents of it are not visible in methods, functions, etc. As return type is inferred from typescript types, the text should also be visible.

### Proposed solution

Extend `returnType` macro (`libs/builder/templates/helpers/type.html.nunj`) to include `@returns` tag contents, excluding type if it was also specified (e.g. `@returns {MyType} some content` should not render `{MyType}` as it's already specified from typescript).

### Alternatives considered

There's no alternatives currently.

**Comment by AdrianKokot** [comment]
Well, it's more like a bug because in documentation there's information that this should be working, but is not (at least from what I've tried in class methods)

**Comment by skoropadas** [comment]
I agree, but I would make an exception for not changing `libs/builder/templates/helpers/type.html.nunj`, as it primarily handles displaying values based on TypeScript code.

The scenario where it's necessary to override the return type using a JSDoc comment seems unlikely, but it could be considered in the future. Therefore, I would simply add the rendering of the `@returns` tag content as it is, alongside the type, so I would add it only for the `libs/builder/templates/helpers/method.html.nunj` template.
