### ISSUE TITLE
[Bug] Wrong title property set, should use backticks

### ISSUE THREAD

**Issue by Nxtivision** [ng-doc/ng-doc#223]
### Is this a regression?

Yes

### Description

When upgrading to v18 (seems really promising!), I had an error with the generated title property. It was set like this by the page-wrapper.component.nunj:

```
const routes: Routes = [{
  path: '',
  component: PageWrapperComponent,
  title: `Gestion d'erreur`,
  children: [
    {
      path: '',
      loadChildren: () => import('./index/page'),
      title: 'Gestion d', erreurs, ',:
      data: {
        icon: '',
      }
    },
  ]
}]
``` 

When remove quotes (for example, using english), the error disappeared.

```
const routes: Routes = [{
  path: '',
  component: PageWrapperComponent,
  title: `Error handling`,
  children: [
    {
      path: '',
      loadChildren: () => import('./index/page'),
      title: 'Error handling',
      data: {
        icon: '',
      }
    },
  ]
}]
```

Shouldn't we have only one title property? And this can be set using backticks instead, to avoid this kind of error ?

Thank you in advance :smile: 

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

20.17.0

### Anything else?

I tried using backticks directly in the `ng-doc.page.ts`. Is it the way to go ?

**Comment by skoropadas** [comment]
Hey thanks for the ticket, yeah that was a type, I'll release a fix in a moment
