### ISSUE TITLE
[Bug] API doesn't link to angular.dev

### ISSUE THREAD

**Issue by beig** [ng-doc/ng-doc#230]
### Is this a regression?

I don't know

### Description

I can't find anything about it in the documentation, but my ng-doc api (version `18.1.1`) doesn't create links to angular.dev

![image](https://github.com/user-attachments/assets/422075ed-4b34-4a71-80a2-1d90bb99effa)

### OS

Windows

### Browser

Chrome

### Node version

v22.3.0

**Comment by skoropadas** [comment]
have you added `ngKeywordsLoader` to your config file?
https://ng-doc.com/docs/writing-content/keywords/loaders#integrating-with-the-angular-documentation
