### ISSUE TITLE
[Bug] at-rule (@) should not be evaluated inside code block

### ISSUE THREAD

**Issue by Nxtivision** [ng-doc/ng-doc#232]
### Is this a regression?

Yes

### Description

Hello!

I've just found a bug while documenting a new directive, and I think this bug will largely affect the documentation :fearful: 

Here is my documentation:

```typescript
/**
 * [...]
 * #### Example in a component's TypeScript:
 *
 * ```typescript
 * import { Component } from '@angular/core';
 * import { OneAvatarDirective, Profile } from '@one/theme/avatar';
 * \@Component({
 *   standalone: true,
 *   selector: 'app-user-avatar',
 *   imports: [OneAvatarDirective],
 *   template: `<button oneBtnAvatar [profile]="userProfile" class="extra-class"></button>`,
 * })
 * export class UserAvatarComponent {
 *   userProfile: Profile = {
 *     id: 'unique-id',
 *     email: 'user@example.com',
 *     firstName: 'John',
 *     lastName: 'Doe',
 *   };
 * }
 * ```
 */
@Directive({
  standalone: true,
  selector: 'button[oneBtnAvatar]',
  hostDirectives: [OneButtonDirective],
})
export class OneAvatarDirective { }
```

As we can see, inside the code block, I need to escape the `@`, or it is evaluated and the rest of the code example does not show in the API, which is annoying. The funny part is that the email is not affected by this behavior.

Can you take a look when you have time? :smile: 

Thx in advance !

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

20.17.0

**Comment by skoropadas** [comment]
Hey, thanks for the ticket, yeah that was a regression, I missed that jsdoc that `ts-morph` uses to parse comments doesn't parse such things correctly
