### ISSUE TITLE
[Bug] NgDocTypeAlias doesn't work as described in the docs

### ISSUE THREAD

**Issue by ms-dosx86** [ng-doc/ng-doc#235]
### Is this a regression?

I don't know

### Description

In the [docs](https://ng-doc.com/docs/writing-content/playground#unrecognized-inputs) there is example of a custom list type usign `NgDocTypeAlias`

```ts
color: {
  type: 'NgDocTypeAlias',
  options: ['primary', 'secondary', 'success', 'danger']
},
```

which doesn't render any options when you try to open the dropdown with the options.

After a couple of hours of investigation it seems like [here](https://github.com/ng-doc/ng-doc/blob/39b20dbe9c2275107adfacc818cec0f7fa48b5a9/libs/app/type-controls/type-alias-control/type-alias-control.component.html#L10) is the problem. A string passed in `NgDocExtractValuePipe` which then passed it into `extractValue` which returns an empty string because

```ts
new Function('return danger')()
```

throws an error. If the option strings passed with quotes 

```ts
options: ["'primary'", "'secondary'", "'success'", "'danger'"],
``` 

then it starts working.

### Please provide the exception or error you saw

```true
No exceptions. The dropdown list doesn't open quietly. I mean, it opens but without options which turns out it to be empty.
```

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

20

**Comment by skoropadas** [comment]
Thanks for the ticket! Yep this is a regression of NgDoc18.
The documentation is correct, and you should not use quotation marks. They are necessary only to resolve simple types, but when you specify values for the control yourself, everything should work as usual.
