### ISSUE TITLE
[Bug] Specifying API Reference Page `route` Causing Asset Not Found

### ISSUE THREAD

**Issue by Char2sGu** [ng-doc/ng-doc#236]
### Is this a regression?

Yes

### Description

When a route is specified in ng-doc.api.ts, api-list.json will be generated under that specific route. However, in the frontend, it still fetches api-list.json at the root, causing a not found.

In other words, when a route is specified as `path`, `api-list.json` is generated at `/assets/ng-doc/path/api-list.json`, however the frontend requests `/assets/ng-doc/api-list.json`, ignoring the route settings.

![image](https://github.com/user-attachments/assets/25ee2046-14db-4bce-8cdd-5f9ecae4670e)
![image](https://github.com/user-attachments/assets/ee2c4041-82a9-4762-adbc-67342180520d)
![image](https://github.com/user-attachments/assets/30c1dd9d-dcdd-4989-8d3f-8e14d501c234)

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

Not Matter

**Comment by skoropadas** [comment]
It took a little time to understand the issue :) but yes, I realized that this is about the case when the `route` is configured directly to `NgDocApi` instead of `NgDocApiScope`. This should be fixed in the next version. Thank you for the ticket!
