### ISSUE TITLE
[Feature] SEO Friendly links

### ISSUE THREAD

**Issue by IKatsuba** [ng-doc/ng-doc#241]
### Description

NgDocSidebar uses NgDocExpander to hide or show sidebar links. When a group collapses, the expander removes all links. This is not SEO-friendly. Robots do not see these links and do not index the related content.
<img width="1054" alt="Screenshot 2024-10-19 at 16 39 14" src="https://github.com/user-attachments/assets/18b9cb94-1dbb-41d4-a966-97e78fd0bea3">

### Proposed solution

Can we use `opacity: 0` or `display: none` for links in Sidebase instead of ngIf?

### Alternatives considered

-

**Comment by skoropadas** [comment]
Yeah, makes sense! Can check it after a vacation

**Comment by skoropadas** [comment]
Should be fixed by [this](https://github.com/ng-doc/ng-doc/commit/3217d5a31168a96c4950b0073a6bb12425e4c54e) commit
