### ISSUE TITLE
[Bug] Version 18.3 not compatible with Angular 19

### ISSUE THREAD

**Issue by NetWin** [ng-doc/ng-doc#247]
### Is this a regression?

No <sub>(i mean, it's not a new bug in ng-doc, it's a breaking change in Angular 😄)</sub>

### Description

[Angular 19](https://github.com/angular/angular/releases/tag/19.0.0) (Released today) made some breaking changes in the way they treat the `this` keyword within templates. It now prefers class member over template variables which leads to a crash while initializing the ng-doc sidebar. 

From the current Angular release:
> `this.foo` property reads no longer refer to template context variables. If you intended to read the template variable, do not use this..

----

<img width="876" alt="Bildschirmfoto 2024-11-19 um 20 44 04" src="https://github.com/user-attachments/assets/7cc1d4dd-3f22-4123-adc7-808a3130eece">

Breaking part here:
https://github.com/ng-doc/ng-doc/blob/main/libs/app/components/sidebar/sidebar.component.html#L4

### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

20

**Comment by skoropadas** [comment]
Yeap this is expected, I'll release a version 19 when nx adds support for Angular 19

**Comment by DaveMBush** [comment]
@skorapadas

I also use NX and upgrading manually was relatively painless. The main thing is to make sure you've been explicitly about standalone components.  A few lint issues after that that are easy to fix.

**Comment by skoropadas** [comment]
@DaveMBush I guess you used `--force` or `--legacyPeerDeps` flag to install dependencies. I just don't use it to make sure all deps are fine and NX has a [lock ](https://github.com/nrwl/nx/blob/bcaef270461649fffa3276d7233142c14edab50e/packages/angular/package.json#L70)for the Angular version, this is why I'm waiting for the new NX version

**Comment by skoropadas** [comment]
I think I'll add the same lock starting from the next major version since every major Angular version breaks compatibility

**Comment by DaveMBush** [comment]
@skoropadas I don't use either of those flags.  I use pnpm and it warns me of mismatched dependencies but I'm not having any issues between NX 20 and Angular 19. In the case of NgDocs I think my main issue I can't get around is with regard to SSR.

**Comment by hutzelknecht** [comment]
@skoropadas nx is already on 19 https://github.com/nrwl/nx/releases/tag/19.8.13! any plans to release ng-doc 19 soon?

**Comment by pierrenedelec** [comment]
https://github.com/nrwl/nx/releases/tag/20.2.0 is released, i'm having same issue unable to run ng-doc with Angular 19.0.3 and NX 20.2.0

**Comment by skoropadas** [comment]
> https://github.com/nrwl/nx/releases/tag/20.2.0 is released, i'm having same issue unable to run ng-doc with Angular 19.0.3 and NX 20.2.0

I'll try to check it today, thanks!
