### ISSUE TITLE
[Bug] `isStandalone` helper does not work with Angulars new default value

### ISSUE THREAD

**Issue by NetWin** [ng-doc/ng-doc#252]
### Is this a regression?

Yes

### Description

Angular changed the default value of the `standalone` component (/pipe/directive) property. 
It's now `true` instead of `false` and the `isStandalone` helper does not support this:

https://github.com/ng-doc/ng-doc/blob/main/libs/builder/helpers/angular/is-standalone.ts#L17

If the property is not available, it should return `true` instead of `false`.

### Steps to reproduce

- Have a playground with a demo component
- Remove the `standalone: true` property from the component decorator
- 😢 

### Screenshots

![image](https://github.com/user-attachments/assets/9d3f600a-257f-4f09-9aab-cacef6e87567)

![image](https://github.com/user-attachments/assets/ad6199d1-a82d-4e58-a66c-cef2fb66be32)

![image](https://github.com/user-attachments/assets/aac4c9fc-8961-48b0-be6d-87fadaaf67f3)

### Please provide the exception or error you saw

```true
✘ [ERROR] NG8002: Can't bind to 'disabled' since it isn't a known property of '<component-selector>'.
1. If '<component-selector>' is an Angular component and it has 'disabled' input, then verify that it is included in the '@Component.imports' of this component.
2. If '<component-selector>' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@Component.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@Component.schemas' of this component. [plugin angular-compiler]

    ng-doc/docs/guides/<component-route>/docs/playgrounds.ts:11:203:
      11 │ ...bounceTime']" [disabled]="properties['disabled']" [smallBorderR...
```

### OS

Windows

### Browser

Chrome

### Node version

20

**Comment by skoropadas** [comment]
Thanks!  Yea it makes sense, I missed that, I'll release a fix in a few minutes!

**Comment by NetWin** [comment]
Thank you 🙏🏼😊
