### ISSUE TITLE
[Bug] Strange behavior on ng-doc 16.3.2

### ISSUE THREAD

**Issue by R-Bower** [ng-doc/ng-doc#58]
### Is this a regression?

Yes

### Description

I'm upgrading to 16.3.2 from Angular 15.  It's gone well so far, but I'm noticing a strange issue when building using webpack.

If I build first using webpack, the ng-doc folder isn't generated properly.  It's missing all of the pages under `guides`.  Example:

```
./.ng-doc/app/ng-doc.routing.ts:3:22-70 - Error: Module not found: Error: Can't resolve '.ng-doc/app/guides/installation/module' in '/Users/rbower/code/qc/qui/qui-components/packages/angular-docs/.ng-doc/app'

./.ng-doc/app/ng-doc.routing.ts:6:22-57 - Error: Module not found: Error: Can't resolve '.ng-doc/app/guides/module' in '/Users/rbower/code/qc/qui/qui-components/packages/angular-docs/.ng-doc/app'
```

It works when I use the `esbuild` builder.  However, I need to use the `webpack` builder because tailwind + scss isn't currently supported, and my docs site uses tailwind for demos.

What's weird is that when I build using esbuild and then switch over to webpack and build, it works just fine, even if I clear the .ng-doc folder between builds. 

### Please provide the exception or error you saw

```true
./.ng-doc/app/ng-doc.routing.ts:3:22-70 - Error: Module not found: Error: Can't resolve '.ng-doc/app/guides/installation/module' in '/Users/rbower/code/qc/qui/qui-components/packages/angular-docs/.ng-doc/app'

./.ng-doc/app/ng-doc.routing.ts:6:22-57 - Error: Module not found: Error: Can't resolve '.ng-doc/app/guides/module' in '/Users/rbower/code/qc/qui/qui-components/packages/angular-docs/.ng-doc/app'
```
```


### OS

Unix (Linux, macOS, etc.)

### Browser

Chrome

### Node version

18.16.0

### Anything else?

_No response_

**Comment by skoropadas** [comment]
Looks like something was not generated correctly, few questions to understand your issue better:

- Did you migrate to 16.3.x using this #57 migration?  
- Does it work if you provide `cache: false` in the `ng-doc.config.ts`?

**Comment by R-Bower** [comment]
I did migrate, yeah.  I also removed all of my page modules and converted every demo component to standalone.  I'll try with cache disabled and see if it fixes the issue.

**Comment by R-Bower** [comment]
Confirmed working with `cache: false`.

**Comment by skoropadas** [comment]
@R-Bower ok great I think we've found the problem, I specifically made it so that the cache could be completely disabled by returning to the process as it was before the cache in case something like this happens, because the cache is quite a big feature and most likely will not work correctly on all projects from the start. I'll try to reproduce this locally and fix it, thank you for the feedback!

**Comment by R-Bower** [comment]
Cool, thanks for the quick response!

**Comment by skoropadas** [comment]
The reason that the project was built correctly after switching the builder is that NgDoc resets the cache after changing the configuration, so I decided to disable the cache function by default, I have not yet been able to reproduce a similar problem on other projects, apparently, its stability depends on the environment. It seems that the only way to solve it is to get a project in which it is reproduced so that it would be possible to debug its behavior and understand what's going on. 

I'm also gonna refactor the builder, reduce the delay between the NgDoc and Angular builders, and maybe slightly increase the build speed, so maybe this problem will go away by itself, anyway will see!

**Comment by R-Bower** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things.

**Comment by skoropadas** [comment]
@R-Bower hey, could you try to enable the cache on version 16.4.x and try to build the app several times? I wonder if this problem has been solved 🤔

**Comment by skoropadas** [comment]
> It was working initially, but fails if I remove the `.ng-doc` folder contents and attempt a fresh build.  I can't get it to work after that.

Got it, thank you 👍 I'll continue checking 🤔

**Comment by R-Bower** [comment]
Feel free to release some pre-release builds and I'll test them for you.

**Comment by skoropadas** [comment]
> Feel free to release some pre-release builds and I'll test them for you.

That would be awesome! Thank you! 😊

**Comment by R-Bower** [comment]
I can get caching to work in dev mode by following these steps:
1. Set `cache: false` in `ng-doc.config.ts`
2. Build
3. Set `cache: true` in `ng-doc.config.ts`
4. Serve in dev mode.

It's quite fast.  Looking forward to when this is fixed :)

**Comment by R-Bower** [comment]
This appears to be working, will keep testing and let you know.

**Comment by skoropadas** [comment]
> This appears to be working, will keep testing and let you know.

Ok, thank you 👍

**Comment by R-Bower** [comment]
So far I've tested the following:
- Start dev mode without .ng-doc folder.
- Start dev mode with .ng-doc folder from previous build.
- Start dev mode with .ng-doc folder, but the folder is empty.
- Build without .ng-doc folder.

Everything seems to be working as expected.

**Comment by R-Bower** [comment]
Anytime, happy to help!

**Comment by R-Bower** [comment]
I thought I commented this yesterday, but apparently it didn't get posted.  The app fails to build in this situation:

1. Create ng-doc page.
2. Start dev mode or build.
3. Stop dev mode.
4. Remove ng-doc page.
5. Start dev mode.

The page can't be found and an error is thrown in `ng-doc.routing.ts`.  The app doesn't compile until the offending route is removed.

**Comment by skoropadas** [comment]
> I thought I commented this yesterday, but apparently it didn't get posted.  The app fails to build in this situation:
> 
> 1. Create ng-doc page.
> 2. Start dev mode or build.
> 3. Stop dev mode.
> 4. Remove ng-doc page.
> 5. Start dev mode.
> 
> The page can't be found and an error is thrown in `.ng-doc/app/ng-doc.routing.ts`.  The app doesn't compile until the offending route is removed from the routes config in this file.  Removing the entire `.ng-doc` folder and restarting also works in this circumstance.

I'll check it, thank you! I also found other bugs related to the cache and auto-rebuild when the cache is enabled. I'll release it with a new feature soon.

**Comment by skoropadas** [comment]
@R-Bower it's not reproducible in my new branch, so maybe I've already fixed it 🙃 I want to test a new feature and changes that I've done and release them tomorrow, so let's wait a bit :)
