### ISSUE TITLE
[Bug] build doesn't exit, causes CI to time out

### ISSUE THREAD

**Issue by R-Bower** [ng-doc/ng-doc#64]
### Is this a regression?

Yes

### Description

The build process doesn't exit, which is causing my CI deployments to fail.  This seems to have been introduced in one of the v16.4.x releases.  

### OS

Unix (Linux, macOS, etc.)

### Browser

None

### Node version

18.14.0

**Comment by skoropadas** [comment]
Again 🤨 it's strange that my CI is working fine, in any case, I'll check it now, thank you!

**Comment by skoropadas** [comment]
yep, I forgot about one line of code during refactoring :) should work now!
