### ISSUE TITLE
[Feature] Custom Breadcrumbs, Page Links

### ISSUE THREAD

**Issue by R-Bower** [ng-doc/ng-doc#66]
### Description

I currently supply my own side navigation, header, breadcrumbs, and prev/forward page links.  

The side nav and header are pretty easy to override, but the breadcrumbs and page links don't have the same customization.  For the breadcrumbs, I force the original elements to hide using `display: none` css and then render my own.  For the page links, I've just styled what you've provided, but I'd like to supply my own if possible.

These elements are contained within the `<router-outlet>`, so overriding them might be an involved process to set up.

### Proposed solution

Give us an option to supply our own breadcrumbs component, much like we can already do for the sidebar and header.

### Alternatives considered

Force the original elements to hide using CSS and then render my own.

**Comment by skoropadas** [comment]
I'll try to release something next week, I'd like to rethink a bit how users can provide custom components for the documentation to exclude default components that are not used from the bundle

**Comment by skoropadas** [comment]
hey, are you gonna replace the table of contents with your own one? I also want to add the ability to replace the table of contents, but I'm thinking about the API for it.

**Comment by R-Bower** [comment]
Yes, ideally I should be able to replace every major component.
