### ISSUE TITLE
[Bug] Playgrounds autogeneration does not support Angular 16 required inputs

### ISSUE THREAD

**Issue by czemar** [ng-doc/ng-doc#68]
### Is this a regression?

No

### Description

New Angular 16 feature with required inputs generates wrong results:
```ts
@Component({
  selector: "ng-doc-playground-1",
  template: `
		<icon [{ required: true }]="properties['icon']" [size]="properties['size']" [strokeWidth]="properties['strokeWidth']" [color]="properties['color']"></icon>
	`,
  standalone: true,
  imports: [CommonModule, pageEntity.playgrounds["IconPlayground"].target],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
```
Docs: [https://angular.io/api/core/Input](https://angular.io/api/core/Input)

### Please provide the exception or error you saw

```true
Error: .ng-doc/docs/guides/docs/playgrounds.ts:18:3 - error NG5002: Opening tag "icon" not terminated.

18   <icon [{ required: true }]="properties['icon']" [size]="properties['size']" [strokeWidth]="properties['strokeWidth']" [color]="properties['color']"></icon>
     ~~~~~~~~~~~~~~~~~~
```

### OS

Unix (Linux, macOS, etc.)

### Browser

None

### Node version

v18.16.0

### Anything else?

Leaving for future improvements :wink:

**Comment by skoropadas** [comment]
Ah I see, I didn't check that after the migration to Angular 16, but I'll fix it as well, thank you!
