### ISSUE TITLE
[Bug] @ng-doc/add fails on brand new angular 16 app

### ISSUE THREAD

**Issue by edumserrano** [ng-doc/ng-doc#69]
### Is this a regression?

I don't know

## Steps to reproduce

- `ng new` to create a new app.
- `ng add @ng-doc/add` as per quick start guide.

## Expected

NgDoc setup to succeed.

## Actual

NgDoc setup fails with the following error message: 

> ℹ Using package manager: npm
✔ Found compatible package version: @ng-doc/add@16.6.3.
✔ Package information loaded.
>
> The package @ng-doc/add@16.6.3 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Cannot find module 'C:\dev\repos\temp\docs-test\node_modules\@angular-devkit\core\src\virtual-fs\host.js'

### Please provide the exception or error you saw

```true
Cannot find module 'C:\dev\repos\temp\docs-test\node_modules@angular-devkit\core\src\virtual-fs\host.js'
```

### OS

Windows

### Browser

None

### Node version

16.19.1

### Anything else?

- tried doing `npm install @angular-devkit/core` and retrying the `ng add @ng-doc/add` command but same result.
- ng version information is:
> Angular CLI: 16.1.1
Node: 16.19.1
Package Manager: npm 9.6.7
OS: win32 x64
- `package.json` state after `ng add @ng-doc/add` command failed:
>   "dependencies": {
    "@angular-devkit/core": "^16.1.1",
    "@angular/animations": "^16.1.0",
    "@angular/common": "^16.1.0",
    "@angular/compiler": "^16.1.0",
    "@angular/core": "^16.1.0",
    "@angular/forms": "^16.1.0",
    "@angular/platform-browser": "^16.1.0",
    "@angular/platform-browser-dynamic": "^16.1.0",
    "@angular/router": "^16.1.0",
    "@ng-doc/add": "^16.6.3",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.1.1",
    "@angular/cli": "~16.1.1",
    "@angular/compiler-cli": "^16.1.0",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.1.3"
  }

**Comment by skoropadas** [comment]
Hey thanks for the bug report, are you angular app is standalone?

**Comment by edumserrano** [comment]
No, I just did `ng new` and on the prompts:

- `Would you like to add Angular routing?`  answered `no`
- `Which stylesheet format would you like to use?` answered `less`

This by default does not create a standalone app.

**Comment by skoropadas** [comment]
Yep, I see. The issue lies with the 'ng-morph' package that I'm using for the schematics. It appears that the newest version of '@angular-devkit/core' used by 'ng-morph' no longer includes 'virtual-fs'. I will submit a pull request to the 'ng-morph' repository to resolve this problem and update it in my library.

As a workaround, you can follow these steps:
- Manually install version 16.0.0 of '@angular-devkit/core' by running the command: 'npm i @angular-devkit/core@16.0.0'.
- After installing, run the schematics using 'ng add @ng-doc/add'. Everything should work fine with this workaround.

**Comment by skoropadas** [comment]
I also found another problem that `parsimmon` package is not installed after adding ng-doc to the project, I'll fix that one in a few minutes

**Comment by edumserrano** [comment]
Thanks. I can confirm the suggested workarounds work. For clarity:
1) ng new
2) npm i @angular-devkit/core@16.0.0
3) npm i parsimmon
4) ng add @ng-doc/add

The above results in a success setup of NgDoc.

**Comment by edumserrano** [comment]
Feel free to close this whenever you want. 

As cheeky little nudge, I've created a question on the discussions Q&A that you might be able to help with https://github.com/ng-doc/ng-doc/discussions/70

**Comment by skoropadas** [comment]
the issue with `parsimmon` was already fixed. this bug is waiting this PR - https://github.com/Tinkoff/ng-morph/pull/76

**Comment by edumserrano** [comment]
Also, not sure it's related with this, but after getting it to work as described above I tried:
`ng g @ng-doc/builder:page "Installation"` 

and got the error: 

`The "path" argument must be of type string. Received undefined`

Is this somehow related or should I open a new issue?

**Comment by skoropadas** [comment]
@edumserrano not sure, looks like it's related to the windows cmd, because usually this message means that schematic command could not understand the current path where you are running it.

I need to check it, but I'm not at home, so I'll be able to do that only on Tuesday, so yes pls create a separate issue 🙏

**Comment by edumserrano** [comment]
I can confirm this is now working as expected on the latest version. Thank you!
