### ISSUE TITLE
[Bug] Can't use ng-doc schematics to create things

### ISSUE THREAD

**Issue by edumserrano** [ng-doc/ng-doc#71]
### Is this a regression?

I don't know

### Description

After creating a brand new angular app and adding ng-doc I can't use the schematics to create ng-doc things.

Steps to reproduce:
1) ng new
2) npm i @angular-devkit/core@16.0.0
3) ng add @ng-doc/add
4) Use some ng-doc generate command like `ng g @ng-doc/builder:page "Installation"` or `ng g @ng-doc/builder:category "Getting Started"`

### Please provide the exception or error you saw

```true
The "path" argument must be of type string. Received undefined
```

### OS

Windows

### Browser

None

### Node version

16.19.1

### Anything else?

- ng version information is:
> Angular CLI: 16.1.1
Node: 16.19.1
Package Manager: npm 9.6.7
OS: win32 x64
- follow up to #69

**Comment by skoropadas** [comment]
I can't reproduce it on either macOS or Windows. I also tried using different terminals like PowerShell and Git Bash, as well as different versions of Angular. Can you please try it again on the latest version of the library? If the issue persists, please create a repository where the problem can be reproduced.

**Comment by edumserrano** [comment]
I've tried on the latest version of the library and the problem is still there. I've created a repro repo and added all the info I could think about to the README. 

Please see [edumserrano/ng-doc-bug](https://github.com/edumserrano/ng-doc-bug)

**Comment by skoropadas** [comment]
@edumserrano I'll check the report, thank you so much!

**Comment by skoropadas** [comment]
Finally, I understood the reason. 😄 I assume that you are calling the command to create a page or category directly in the root folder of the repo, which is why the error occurs because apparently the path is not resolved correctly.
By default, NgDoc will look for pages and categories in your `sourceRoot` folder (which is set to 'src' by default). That's why I didn't even test the possibility of calling schematics in the repo's root directory.

However, if you try calling it in `src/app` or `src`, for example, everything should work. In any case, this is a bug, and I will fix it, but thank you very much for your help! 👍

**Comment by edumserrano** [comment]
I can confirm your workaround works. Executing the commands from `src` folder instead of the root of the repo does work
![image](https://github.com/ng-doc/ng-doc/assets/15857357/95d438f6-a3d4-4ae3-8009-498e6ccd52f2)

As you said, it would be nice to have it work from the root of the repo  =)

**Comment by skoropadas** [comment]
@edumserrano Yes, I will fix it to avoid misunderstandings, but keep in mind that calling at the root of the repository will create a category or page within the repository's root, and NgDoc will not see it or display it in the application until you change the `pages` property inside the `ng-doc.config.ts` file to the root directory. I think I will start handling such cases and offer action confirmations if the user tries to create a page in a directory that NgDoc does not process.

You can also read about pages path [here](https://ng-doc.com/docs/getting-started/configuration#documentation-folder)

**Comment by edumserrano** [comment]
Wouldn't then a parameter be helpful here? So you could do `ng g @ng-doc/builder:page "Installation" <optional location parameter>` ?

This way it would be a non breaking change in the sense that by default the location would act as "the current folder", meaning as if you had run the command as  `ng g @ng-doc/builder:page "Installation" .` (note the dot at the end of the command).

Then if you're not in the "right directory" you could still do `ng g @ng-doc/builder:page "Installation" src/app` for instance ?

I do think that giving a warning in case the chosen directory is invalid/won't be picked up by NgDoc, is a good idea.

**Comment by skoropadas** [comment]
@edumserrano Actually this parameter is already available it's a basic schematic's functionality, so instead of changing the current folder you can run the following command: `ng g @ng-doc/builder:page "Installation" --path=src/app`

**Comment by edumserrano** [comment]
Good to know, perhaps that could go into the warning message you're planning to add? Try to guide the user into a success path by saying that "the path you're trying to use won't work, perhaps you meant to run with --path to specify the path where the NgDoc app is" . Something that would help noobies like me know better. Just a thought.

**Comment by skoropadas** [comment]
@edumserrano that's what I will do thank you for the suggestion! 🤝

**Comment by skoropadas** [comment]
I've checked the source code again and looks like I can't add the warning message because I don't know the root folder of the project when the user runs schematic command so the config file cannot be found, so I'll just add a warning to documentation and of course, fix the bug.
