### ISSUE TITLE
[Bug] wrong use of title property

### ISSUE THREAD

**Issue by Nxtivision** [ng-doc/ng-doc#73]
### Is this a regression?

No

### Description

As a french speaker, we sometimes use an apostrophe like "Exemple d'un composant".

However, when I introduce an apostrophe, it results in a error

### Please provide the exception or error you saw

```true
`
.ng-doc\public-doc\guides\utilities\spacing\module.ts: Unterminated string constant. (33:64)

component: DynamicComponent,
> 33 |                     title: 'Classes utilitaires d', espacement, ',: 
        |                                                             ^
```
```


### OS

Windows

### Browser

Chrome

### Node version

18.16.0

### Anything else?

_No response_

**Comment by skoropadas** [comment]
looks like escaping doesn't work well, should be easy to fix, I'll fix it tomorrow, thanks for the bug report!
