### ISSUE TITLE
[Bug] multi-selectors create multi container

### ISSUE THREAD

**Issue by Nxtivision** [ng-doc/ng-doc#79]
### Is this a regression?

I don't know

### Description

Here is a funny bug!
I want to test my buttons, and to create an interactive playground, I use a directive as target:

### Directive as target

```typescript
@Directive({
  selector:
    'button[mat-button], button[mat-flat-button], button[mat-stroked-button]',
  standalone: true,
})
export class ButtonDirective {
  @Input() color: ThemePalette = 'primary';
  @Input() disabled = false;
}
```

### NgDoc config used

```typescript
const ButtonsPage: NgDocPage = {
  title: `Buttons`,
  mdFile: './index.md',
  category: OneThemeCategory,
  imports: [MatButtonModule],
  playgrounds: {
    ButtonPlayground: {
      target: ButtonDirective,
      template: `
      <div style='display: flex; gap: 8px;'>
        <button mat-button>Normal</button>
        <button mat-flat-button>Flat</button>
        <button mat-stroked-button>Stroked</button>
      </div>
      `,
    },
  },
};
```

And it gives the following result:

![2023-07-05_14h36_33](https://github.com/ng-doc/ng-doc/assets/89700030/bb07e0f9-4cf8-4ada-bc0e-01dc2c77dba7)

### Please provide the exception or error you saw

```true
As we can see, we have a duplicated container for each element in the selector inside the Directive. Maybe it is designed as intended, but in this case, each change in inputs will change only one element for each container.

If it was designed to work like this, it could be interesting to have an option to `regroup` the active elements (those where the input changes are applied)
```

### OS

Windows

### Browser

Chrome

### Node version

18.16.0

### Anything else?

(I know I post a lot of issues in your repo, but as you can notice, I push the limits of your library 😄 )

**Comment by skoropadas** [comment]
Don't worry, I'm glad someone started raising bugs and requesting different features. It will only make the project better! :)

Regarding the playground, you are using the template field incorrectly. The template can only contain one selector for the displayed component or directive. If your component supports multiple selectors, you should use the `ng-doc-selector` tag. It will automatically replace the selector with your component selector, and the playground will start displaying demos for multiple variants at once.

So your config should look like this:

```typescript
const ButtonsPage: NgDocPage = {
  title: `Buttons`,
  mdFile: './index.md',
  category: OneThemeCategory,
  imports: [MatButtonModule],
  playgrounds: {
    ButtonPlayground: {
      target: ButtonDirective,
      template: `
        <ng-doc-selector>Button</ng-doc-selector>
      `,
    },
  },
};
```

**Comment by Nxtivision** [comment]
OK, it works correctly! I thought it could only take one selector at a time, but `ng-doc-selector` is more clever than I thought :) Also, it is written in your documentation... My bad, I'm closing this!

**Comment by skoropadas** [comment]
No problem! :) Having just one component for one selector is much easier for the end user. The idea was to allow the user to play around with the component and then simply copy its code with a single button click and paste it into their own application.
