### ISSUE TITLE
[Feature] Extend code display functionality

### ISSUE THREAD

**Issue by fil0157** [ng-doc/ng-doc#83]
### Description

Periodically we make wrappers for components in the demo and playgrounds, the code of these wrappers is not necessary for the components to work, we could hide it in the displayed code so as not to confuse the user of the library.

### Proposed solution

You can make keywords for example: `ng-doc-ignore-next-line` which will work like `ts-ignore` and `eslint-disable-next-line`. The proposed name is an example. 
Example:

``` typescript
@Component({
	selector: 'di-checkbox-group-demo',
	standalone: true,
	imports: [
		CommonModule,
		CheckboxComponent, 
		// @ng-doc-ignore-next-line
		ModelInfoComponent, 
		ReactiveFormsModule, 
		CheckboxGroupComponent
	],
	template: `
		<!-- @ng-doc-ignore-next-line -->
		<di-model-info [control]="control">
			<di-checkbox-group [formControl]="control">
				<di-checkbox *ngFor="let item of items" [value]="item">{{ item }}</di-checkbox>
			</di-checkbox-group>
		<!-- @ng-doc-ignore-next-line -->
		</di-model-info>
	`,
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CheckboxGroupDemoComponent {
	control: FormControl<string[] | null> = new FormControl<string[]>([FRUIT_NAMES[2]]);
	items: string[] = FRUIT_NAMES;
}
```

### Alternatives considered

You can also make a similar functionality for multiple hiding rows.

**Comment by skoropadas** [comment]
It will be added after I finish a small refactoring
