### ISSUE TITLE
Lean build with only Markdown + routing features [Feature] 

### ISSUE THREAD

**Issue by R-Bower** [ng-doc/ng-doc#88]
### Description

I'm interested in an extremely slim build of ng-doc.  I'm mostly using it for its ability to use Angular components in markdown, which is a huge boon to my documentation authoring experience.  

### Proposed solution

How hard would it be to extract just the markdown capabilities of this library? I'm purely talking just rendering an Angular component from markdown. No demos, no playgrounds.  At that, would this have a noticeable impact on the total build or hot reload time?

### Alternatives considered

Astro + AnalogJS + MDX, but there are far too many limitations with that setup in its current form.

**Comment by R-Bower** [comment]
I've observed that a fresh ng-doc application seems to reload significantly faster in dev mode than an application with dozens of demos.  This is true even if the changed page doesn't contain any demos.  It seems like ng-doc is rebuilding the entire application whenever a change occurs.  Can you confirm whether this is true?

**Comment by skoropadas** [comment]
Not sure about using `Prism`, code for demos is processed using `highlightjs` on the builder side, and on the client-side, it's simply styled using CSS. The only reason why `highlightjs` exists on the application side is for playgrounds, but I could potentially implement lazy loading.

Regarding recompilation, if you only change one page, the builder will recompile that page and its dependencies. Dependencies are calculated differently based on the type of changed files. For example, if you change the `ng-doc.page.ts` file, the builder will recompile the modified page entirely, as well as all modules of parent categories and all pages that depend on the modified one via keywords.

However, if you change the Markdown content, the builder will only recompile the current page and update global indexes for search.

After that, it depends on Angular to decide what it needs to recompile. But I think it's worth checking if Angular is recompiling anything unnecessary.

**Comment by skoropadas** [comment]
I've decided not to add a separate module. I've been planning a complete transition to standalone components for quite some time, so I'll be adding new providers and releasing it as a separate feature, closing this ticket and #66.

**Comment by skoropadas** [comment]
I have completed everything that was required for both tickets (#88, #66). The only thing left is to update the schematics. The schematics are awaiting this pull request (https://github.com/taiga-family/ng-morph/pull/105), after which I will release the update.
