### ISSUE TITLE
[Feature] new config property in Page to update current route configuration

### ISSUE THREAD

**Issue by Nxtivision** [ng-doc/ng-doc#89]
### Description

I would like to test a component but one of its key feature is the use of data coming from a Resolver. The annoying thing is that I can't update the current route to add this resolver and see the result.

### Proposed solution

```
const UsagePage: NgDocPage = {
  title: `Usage`,
  mdFile: './index.md',
  category: AutoTableCategory,
  keyword: 'AutoTableUsage',
  order: 2,
  additionalRouteConfig: { // This new config property
    resolve: {
      books: MyBooksResolver
    }
  },
  demos: {
    AutoTablesComponent,
  },
};
```

And use this additionalRouteConfig to merge with the current generated routeConfig. What do you think about this ? :)

### Alternatives considered

I tried to create a "simulation" of routing, by using `resetConfig` and `navigate` on the same URL. However, I will have to keep all existing route config and update the current one, which is really difficult because of the amount of route dynamically generated and a simple change in my tree could break the example

**Comment by skoropadas** [comment]
I suppose that to use a resolver, you also need to define the `route` property in the page configuration, for example, `route: 'usage/:books'`, but I don't see it in your example. Anyway, give me some time to think about a possible solution.

**Comment by skoropadas** [comment]
Yeah I see, give some time to implement that, probably I'll extend `route` property so you'll be able to provide `Route` config in addition to `string`
