### ISSUE TITLE
[Feature] Accept inputs from metadata, not only from @Input

### ISSUE THREAD

**Issue by Nxtivision** [ng-doc/ng-doc#97]
### Description

I need a feature in NgDoc to finally be satisfied with my documentation!

In [this repository](https://nxtivision-ngdocsandbox-vvwt74pm7to.ws-eu103.gitpod.io/), corresponding to the work in issue #96, I notice that the inputs coming from my metadata `@Component` are not taken into account. Only `@Input` are recognized. Is there a way to include them?

### Proposed solution

```typescript
@Component({
  selector: 'one-forms-input-text',
  templateUrl: './text.component.html',
  styles: [],
  providers: [FORM_CONTROL_PROVIDER],
  inputs: [
    // I would like these to be recognized as well
    ...MIXIN_METADATA_CVA_CONNECTOR.inputs,
    ...MIXIN_METADATA_LENGTH.inputs,
    ...MIXIN_METADATA_ERROR_STATE_MATCHER.inputs,
  ],
  outputs: [...MIXIN_GLOBAL_OUTPUTS.outputs],
  standalone: true,
  imports: [
    // ...
  ],
})
export class TextComponent extends mixinCVAConnector(
  mixinGlobalOutputs(mixinLength(mixinErrorStateMatcher(Base)))
) { }
```

### Alternatives considered

Finding the definition of these inputs is likely to be quite difficult, so I'm wondering if there shouldn't be a `controls` option to provide mappings between inputs and definitions that are hard to find automatically. Ideally, it would be automatic, but it could be complicated.

**Comment by Nxtivision** [comment]
Thank you, that sounds interesting! At the same time, it could help us determine which inputs we want to display and which ones we'd prefer to ignore, should we decide to delve deeper.

I've explored numerous ways to utilize mixins in Angular, even studying the Angular Material source code. However, it's quite intricate. I'm considering trying hostDirectives, but I'm uncertain if that would be effective...

**Comment by skoropadas** [comment]
Originally, I meant that the `controls ` field would be an extension to what NgDoc defines automatically, i.e. all inputs that NgDoc has autonomously identified, plus those you add in the `controls ` field. This way, you could add new inputs or modify existing ones by including them in the `controls ` field with a different type.
For hiding certain inputs, I would prefer a separate property like `hideInputs ` or `ignoreInputs `which would allow passing multiple values as a string, this way would provide more flexibility and ease of use.
